version: '3'
services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306
    volumes:
     - ../../setup.sql:/docker-entrypoint-initdb.d/setup.sql
     - ./sql:/var/lib/mysql
    environment:
      MYSQL_USER: app
      MYSQL_DATABASE: techtalks
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
  adminer: # For sql administration
    links:
      - mysql
    image: adminer
    ports:
      - 3739:8080
  server:
    image: node
    entrypoint: # This allows us to not need a custom dockerfile for this setup
      - bash
      - "-c"
      - "npm install && npm start"
    environment:
      # Database
      DBHOST: "mysql"
      DBUSER: "app"
      DBPASS: "password"
      DBNAME: "techtalks"
      # Email information
      #MAILUSER: ""
      #MAILPASS: ""
      # JWT
      JWTKEY: "hitormiss"
      # Admin Login
      AUNAME: "admin"
      APASS: "admin"
    working_dir: /srv/techtalks-server
    links:
      - mysql
    ports:
      - 9000
    volumes:
      - ../../api:/srv/techtalks-server
  webui: # Comments above most likely apply here as well
    image: node
    entrypoint: 
      - bash
      - "-c"
      - "npm install && npm start"
    working_dir: /srv/techtalks-frontend
    links:
      - server
    ports:
      - 3000:3000
    volumes:
      - ../../client:/srv/techtalks-frontend
