kind: pipeline
name: default

steps:
  - name: setup
    image: node:11
    volumes:
      - name: cache
        path: /tmp/cache
    when:
      event: [push, pull_request, tag, deployment]
    commands:
      - cd client
      - npm install

  - name: build
    image: node:11
    group: testing
    volumes:
      - name: cache
        path: /tmp/cache
    when:
      event: [push, pull_request, tag, deployment]
    commands:
      - cd client
      - npm run build

# TODO deploy! :D
# client/build må lastes opp og serveres med nginx satt opp for å servere react
# Jeg har skrevet nginx for å anta at den ligger i ../../client/build, bare for at det er lettere å teste lokalt
# api også
# se docker/production/docker-compose.yml, bruk gjerne den

volumes:
  - name: cache
    host:
      path: /opt/drone/cache
