branch-defaults:
  eb:
    environment: techtalks
    group_suffix: null
environment-defaults:
  techtalks-dev:
    branch: eb
    repository: https://github.com/dotkom/techtalks2
global:
  application_name: techtalks
  branch: eb
  default_ec2_keyname: testkey
  default_platform: 64bit Amazon Linux 2 v5.2.0 running Node.js 12
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: https://github.com/dotkom/techtalks2
  sc: git
  workspace_type: Application
