FROM node:12-alpine

LABEL maintainer="ekskom@online.ntnu.no"
LABEL project="techtalks2"

ENV WORKDIR=/srv/app
ENV NODE_ENV=production
ENV PROJECT_ROOT=./api

WORKDIR ${WORKDIR}

# Install dependencies
COPY ${PROJECT_ROOT}/package.json .
COPY ${PROJECT_ROOT}/package-lock.json .
RUN npm install

# Copy project files
COPY ${PROJECT_ROOT} .

EXPOSE 9000

CMD ["npm", "start"]