FROM alpine:3.8

RUN apk add --no-cache nginx

RUN apk add --update --no-cache nodejs npm

COPY ./client/ /tmp
ENV PORT=80
RUN cd /tmp && npm install && npm run build && mv build /var/www/techtalks-frontend

COPY ./docker/production/nginx.conf /etc/nginx/nginx.conf

ENTRYPOINT nginx
