name: Lint and Test
on: [push]
jobs:
  check-frontend:
    name: Lint and test frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Cache frontend dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-frontend-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-frontend
          working-directory: ./frontend
      
      - name: Install frontend dependencies
        run: npm install
        working-directory: ./frontend

      - name: Run ESLint
        run: npm run lint-eslint
        working-directory: ./frontend
        
      - name: Run Prettier
        run: npm run lint-prettier
        working-directory: ./frontend
      
      - name: Run tests
        run: npm test -- --watchAll=false
        working-directory: ./frontend
  
  check-server:
    name: Lint server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: Cache server dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-server-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-server

      - name: Install server dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint-eslint

      - name: Run Prettier
        run: npm run lint-prettier