name: Lint and Test
on: [push]
jobs:
  check-frontend:
    name: Lint and test frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Cache node dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node
      
      - name: Install frontend dependencies
        run: npm install
        working-directory: ./frontend

      - name: Run ESLint
        run: npm run lint-eslint
        working-directory: ./frontend
        
      - name: Run Prettier
        run: npm run lint-prettier
        working-directory: ./frontend
      
      - name: Run tests
        run: npm test -- --watchAll=false
        working-directory: ./frontend

  check-server:
    name: Lint server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: Cache node dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node

      - name: Install server dependencies
        run: npm install
        working-directory: ./backend

      - name: Run ESLint
        run: npm run lint-eslint
        working-directory: ./backend

      - name: Run Prettier
        run: npm run lint-prettier
        working-directory: ./backend